const { BN } = require('web3').utils;

const ECOSYSTEM_FUND = 1;
const PRIVATE_OFFERING_1 = 3;
const PRIVATE_OFFERING_2 = 4;
const FOUNDATION_REWARD = 5;

const poolNames = {
    [ECOSYSTEM_FUND]: 'ECOSYSTEM_FUND',
    [PRIVATE_OFFERING_1]: 'PRIVATE_OFFERING_1',
    [PRIVATE_OFFERING_2]: 'PRIVATE_OFFERING_2',
    [FOUNDATION_REWARD]: 'FOUNDATION_REWARD',
};

const pools = [ECOSYSTEM_FUND, PRIVATE_OFFERING_1, PRIVATE_OFFERING_2, FOUNDATION_REWARD];

const DAY_IN_SECONDS = new BN(86400);

module.exports = {
    ECOSYSTEM_FUND,
    PRIVATE_OFFERING_1,
    PRIVATE_OFFERING_2,
    FOUNDATION_REWARD,
    poolNames,
    pools,
    DAY_IN_SECONDS,
};
