const REWARD_FOR_STAKING = 1;
const ECOSYSTEM_FUND = 2;
const PRIVATE_OFFERING = 4;
const FOUNDATION_REWARD = 5;

const poolNames = {
    [REWARD_FOR_STAKING]: 'REWARD_FOR_STAKING',
    [ECOSYSTEM_FUND]: 'ECOSYSTEM_FUND',
    [PRIVATE_OFFERING]: 'PRIVATE_OFFERING',
    [FOUNDATION_REWARD]: 'FOUNDATION_REWARD',
};
const pools = [REWARD_FOR_STAKING, ECOSYSTEM_FUND, PRIVATE_OFFERING, FOUNDATION_REWARD];

module.exports = {
    REWARD_FOR_STAKING,
    ECOSYSTEM_FUND,
    PRIVATE_OFFERING,
    FOUNDATION_REWARD,
    poolNames,
    pools,
};
